### Leitura do dataset

In [17]:
from lib.view import Explorer

exp = Explorer("./data/dicionario_PNS_microdados_2019.xls")
exp.print_module_len()

Modulo: C tem 18 atributos
Modulo: D tem 18 atributos
Modulo: F tem 4 atributos
Modulo: I tem 14 atributos
Modulo: J tem 64 atributos
Modulo: P tem 143 atributos
Modulo: Q tem 236 atributos
Total: 497

In [14]:
exp.print_variables_per_module()

Modulo: C

Condição no domicílio | C004

Sexo | C006

Dia de nascimento | C00701

Mês de nascimento | C00702

Ano de nascimento | C00703

Idade do morador na data de referência | C008

Cor ou raça | C009

Cônjuge ou companheiro(a) mora em nesse domicílio. | C01001

Número de ordem do cônjuge ou companheiro(a) | C010010

Cônjuge ou companheiro(a) mora em outro domicílio. | C013

Qual é a natureza dessa união?  | C014

Esta união é registrada em cartório?  | C015

Foi realizada cerimônia religiosa para esta união?  | C016

___já viveu com cônjuge ou companheiro (a) antes?  | C017

Que idade ___tinha quando começou a viver com seu(sua) primeiro(a)/único(a) marido (mulher) ou companheiro(a)?   | C018

Que idade ___tinha quando começou a viver com seu(sua) primeiro(a)/único(a) marido (mulher) ou companheiro(a)?    | C01801

Qual é o estado civil de ___?  | C011

Informante do Módulo C | C012


 ---X---

Modulo: D

Sabe ler e escrever | D001

Frequenta escola ou creche | D00201

A escola que frequenta é da | D00202

Qual é o curso que frequenta | D00301

 Esse curso que ___ frequenta é dividido em | D00501

Qual é o ano/semestre/série que ___frequenta? | D006

Qual é a etapa do ensino fundamental que ___ frequenta | D00601

 ___já concluiu algum outro curso superior de graduação | D007

Anteriormente ___frequentou escola ou creche | D008

Qual foi o curso mais elevado que ___frequentou  | D00901

A duração deste curso que ___frequentou anteriormente era de | D010

Este curso que ___ frequentou anteriormente era dividido em | D01101

concluiu, com aprovação, pelo menos o primeiro ano/semestre/série deste curso que frequentou  | D01201

Qual foi o último ano/semestre/série que ___ concluiu, com aprovação, neste curso que frequentou  | D01301

Qual foi a etapa de ensino fundamental que ___frequentou | D01302

___concluiu os anos iniciais deste curso que frequentou  | D01303

___concluiu este curso que frequentou  | D014

Informante do Módulo D | D015


 ---X---

Modulo: F

Em (mês da pesquisa) ___ recebia normalmente rendimento de aposentadoria ou pensão de instituto de previdência federal (INSS), estadual, municipal, ou do governo federal, estadual, municipal? | F001011

Em (mês da pesquisa), ___ recebia normalmente rendimento de pensão alimentícia, doação ou mesada em dinheiro de pessoa que não morava no domicílio? | F007011

Em (mês da pesquisa), ___ recebia normalmente rendimento de aluguel ou arrendamento? | F008011

Informante do Módulo F | F016


 ---X---

Modulo: I

tem algum plano odontológico particular, de empresa ou órgão público? | I00101

tem algum plano de saúde médico particular, de empresa ou órgão público? | I00102

Quantos? | I001021

Quem é o titular do plano de saúde médico (único ou principal)? | I00103

Nº de ordem do titular  | I001031

Há quanto tempo sem interrupção _____ possui esse plano de saúde (único ou principal)?  | I005

 ___ considera este plano de saúde:  | I006

O plano de saúde médico (único ou principal) que _____ possui é de instituição de assistência de servidor público (municipal, estadual ou militar)?  | I004

O plano de saúde (único ou principal) de assistência médica que ___ possui dá direito a consultas | I00401

O plano de saúde (único ou principal) de assistência médica que ___ possui dá direito a exames | I00402

O plano de saúde (único ou principal) de assistência médica que ___ possui dá direito a internações | I00403

O plano de saúde (único ou principal) de assistência médica que ___ possui dá direito a partos | I00404

Quem paga a mensalidade deste plano de saúde? | I010010

Informante do Módulo I | I012


 ---X---

Modulo: J

De um modo geral, como é o estado de saúde de________ | J001

Considerando saúde como um estado de bem-estar físico e mental, e não somente a ausência de doenças, como é o estado de saúde de _____________?  | J00101

 Nas duas últimas semanas, ___ deixou de realizar quaisquer de suas atividades habituais (trabalhar, ir à escola, brincar, afazeres domésticos etc.) por motivo da própria saúde | J002

Nas duas últimas semanas, quantos dias _____ deixou de realizar suas atividades habituais, por motivo da própria saúde | J003

 Qual foi o principal motivo de saúde que impediu ___ de realizar suas atividades habituais nas duas últimas semanas  | J00402

Este motivo de saúde estava relacionado ao trabalho | J00404

Nas duas últimas semanas___ esteve acamado (a) | J005

Nas duas últimas semanas, quantos dias _____ esteve acamado (a) | J006

Algum médico já deu o diagnóstico de alguma doença crônica, física ou mental, ou doença de longa duração (de mais de 6 meses de duração) a ___ | J007

Alguma dessas doenças limita de alguma forma suas atividades habituais (trabalhar, ir à escola, brincar, afazeres domésticos, etc.) | J00801

 ___ costuma procurar o mesmo lugar, mesmo médico ou mesmo serviço de saúde quando precisa de atendimento de saúde | J009

Quando está doente ou precisando de atendimento de saúde___ costuma procurar | J01002

Quando ____ consultou um médico pela última vez | J01101

Quando ___ consultou um dentista pela última vez | J01301

Nas duas últimas semanas, ___ procurou algum lugar, serviço ou profissional de saúde para atendimento relacionado à própria saúde | J014

Qual foi o motivo principal pelo qual ___ procurou atendimento relacionado à própria saúde nas duas últimas semanas | J01502

Onde ___ procurou o primeiro atendimento de saúde por este motivo nas duas últimas semanas | J01602

Nessa primeira vez que procurou atendimento de saúde por este motivo, nas duas últimas semanas | J01701

Por que motivo ___ não foi atendido(a) na primeira vez que procurou atendimento de saúde nas duas últimas semanas | J01802

Nas duas últimas semanas, quantas vezes ___ voltou a procurar atendimento de saúde por este mesmo motivo | J019

Onde ___ procurou o último atendimento de saúde por este motivo nas duas últimas semanas | J02002

 Nessa última vez que procurou atendimento de saúde por este motivo, nas duas últimas semanas, ___ foi atendido (a) | J021

Por que motivo ___ não foi atendido (a) nessa última vez que procurou atendimento de saúde nas duas últimas semanas | J022010

 Este serviço de saúde onde___ foi atendido era: | J023

 Este atendimento de saúde de ___ foi coberto por algum plano de saúde | J024

 ___ pagou algum valor por este atendimento de saúde recebido nas duas últimas semanas  | J025

O atendimento de ___ foi feito pelo SUS | J026

Qual foi o principal atendimento de saúde que ___ recebeu? | J02702

 Neste atendimento de ___, foi receitado algum medicamento | J02901

 __conseguiu obter os medicamentos receitados? (Leia as opções de resposta) | J03001

Qual o principal motivo de ___ não ter conseguido obter todos os medicamentos receitados | J03102

Algum dos medicamentos foi coberto por plano de saúde | J032

Algum dos medicamentos foi obtido no programa Aqui Tem Farmácia Popular | J03301

Algum dos medicamentos foi obtido em serviço público de saúde | J034

 ___ pagou algum valor pelos medicamentos | J035

Nas duas últimas semanas, por que motivo ___ não procurou serviço de saúde | J03602

Nos últimos 12 meses, ___ ficou internado(a) em hospital por 24 horas ou mais | J037

Nos últimos 12 meses, quantas vezes ___ esteve internado(a) | J038

Qual foi o principal atendimento de saúde que ___recebeu quando esteve internado(a) (pela última vez) nos doze últimos meses | J039

Quanto tempo em meses o morador ficou internado | J04001

Quanto tempo em dias o morador ficou internado | J04002

O estabelecimento de saúde em que ___ esteve internado(a) pela última vez nos últimos 12 meses era | J041

A última internação de ___ nos últimos 12 meses foi coberta por algum plano de saúde | J042

 ___ pagou algum valor por esta última internação? (Entrevistador: se o(a) entrevistado(a) responder que pagou, mas teve reembolso total, marque a opção 2)  | J043

Esta última internação de ___ foi feita através do Sistema Único de Saúde (SUS) | J044

Nos últimos 12 meses, ___ teve atendimento de urgência ou emergência no domicílio | J046

Este atendimento foi coberto por algum plano de saúde | J047

___pagou algum valor por este atendimento? (Entrevistador: se o(a) entrevistado(a) responder que pagou, mas teve reembolso total, marque a opção 2)  | J048

Este atendimento foi feito através do Sistema Único de Saúde (SUS) | J049

Neste atendimento, ___ foi transportado por ambulância para um serviço de saúde | J051

O transporte foi feito por | J052

Nos últimos doze meses, ___ utilizou tratamento como acupuntura, homeopatia, plantas medicinais e fitoterapia, meditação, yoga, tai chi chuan, lian gong ou outra prática integrativa e complementar a saúde? | J05301

Qual tratamento _________ fez uso Acupuntura | J05402

Qual tratamento _________ fez uso Homeopatia | J05403

Qual tratamento _________ fez uso plantas medicinais e fitoterapia | J05404

Qual tratamento _________ fez uso auriculoterapia | J05405

Qual tratamento _________ fez uso meditação | J05406

Qual tratamento _________ fez uso Yoga | J05407

Qual tratamento _________ fez uso Tai chi chuan, Lian gong, Qi gong | J05408

Qual tratamento _________ fez uso Terapia comunitária integrativa | J05409

Qual tratamento _________ fez uso Outro | J054010

___ pagou algum valor por este(s) tratamento(s)  | J056

Este(s) tratamento(s) foi (foram) feito(s) através do Sistema Único de Saúde (SUS): | J057

Informante do Módulo J | J060


 ---X---

Modulo: P

O(A) Sr(a) sabe seu peso?  | P00102

Peso - Informado (em kg)
(3 inteiros e 1 casa decimal) | P00103

Quanto tempo faz que o(a) Sr(a) se pesou da última vez?  | P00201

O(A) Sr(a) sabe sua altura? (mesmo que seja valor aproximado)  | P00402

Altura - Informada (em cm)
(3 inteiros) | P00403

A Sra está grávida no momento? | P005

Ontem o(a) Sr(a) comeu arroz, macarrão, polenta, cuscuz ou milho verde.  | P00601

Batata comum, mandioca/aipim/macaxeira, cará ou inhame. | P00602

Feijão, ervilha, lentilha ou grão de bico. | P00603

Carne de boi, porco, frango, peixe | P00604

Ovo (frito, cozido ou mexido ).  | P00605

Alface, couve, brócolis, agrião ou espinfre. | P00607

Abóbora, cenoura, batata doce ou quiabo/caruru.  | P00608

Tomate, pepino, abobrinha, berinjela, chuchu ou beterraba.  | P00609

Mamão, manga, melão amarelo ou pequi.  | P00610

Laranja, banana, maçã, abacaxi.  | P00611

Leite | P00612

Amendoim, castanha de caju ou castanha do Brasil/Pará  | P00613

ONTEM o(a) Sr(a) tomou ou comeu:Refrigerante | P00614

Suco de fruta em caixinha ou lata ou refresco em pó.  | P00615

 Bebida achocolatada ou iogurte com sabor.  | P00616

Salgadinho de pacote ou biscoito/bolacha salgado. | P00617

Biscoito/bolacha doce ou recheado ou bolo de pacote.  | P00618

Sorvete, chocolate, gelatina, flan ou outra sobremesa industrializada. | P00619

Salsicha, linguiça, mortadela ou presunto.  | P00620

Pão de forma, de cachorro-quente ou de hambúrguer. | P00621

Margarina, maionese, ketchup ou outros molhos industrializados.  | P00622

Macarrão instantâneo, sopa de pacote, lasanha congelada ou outro prato congelado comprado pronto industrilizado. | P00623

Em quantos dias da semana o(a) Sr(a) costuma comer feijão?  | P006

Em quantos dias da semana, o(a) Sr(a) costuma comer pelo menos um tipo de verdura ou legume (sem contar batata, mandioca, cará ou inhame) como alface, tomate, couve, cenoura, chuchu, berinjela, abobrinha?  | P00901

Em geral, o(a) Sr(a) costuma comer esse tipo de verdura ou legume:  | P01001

Em quantos dias da semana o(a) Sr(a) costuma comer carne vermelha (boi, porco, cabrito, bode, ovelha etc.)?  | P01101

Em quantos dias da semana o(a) Sr(a) costuma comer frango/galinha?  | P013

Em quantos dias da semana o(a) Sr(a) costuma comer peixe?  | P015

Em quantos dias da semana o(a) Sr(a) costuma tomar suco de caixinha/lata ou refresco em pó ?  | P02001

Que tipo de suco de caixinha/lata ou refresco em pó o(a) Sr(a) costuma tomar? (Ler as opções de resposta)  | P02101

Em quantos dias da semana o(a) Sr(a) costuma tomar suco de fruta natural (incluída a polpa de fruta congelada)?  | P01601

Em quantos dias da semana o(a) Sr(a) costuma comer frutas?  | P018

Em geral, quantas vezes por dia o(a) Sr(a) come frutas?  | P019

Em quantos dias da semana o(a) Sr(a) costuma tomar refrigerante?  | P02002

Que tipo de refrigerante o(a) Sr(a) costuma tomar?  | P02102

Em quantos dias da semana o(a) Sr(a) costuma tomar leite? (de origem animal: vaca, cabra, búfala etc.)  | P023

Que tipo de leite o(a) Sr(a) costuma tomar?  | P02401

Em quantos dias da semana o(a) Sr(a) costuma comer alimentos doces como biscoito/bolacha recheado, chocolate, gelatina, balas e outros? | P02501

Em quantos dias da semana o(a) Sr(a) costuma substituir a refeição do almoço por lanches rápidos como sanduíches, salgados, pizza, cachorro quente, etc?  | P02602

Considerando a comida preparada na hora e os alimentos industrializados, o(a) Sr(a) acha que o seu consumo de sal é: | P02601

Com que frequência o(a) Sr(a) costuma consumir alguma bebida alcoólica? | P027

Quantos dias por semana o(a) Sr(a) costuma consumir alguma bebida alcoólica?  | P02801

Em geral, no dia que o(a) Sr(a) bebe, quantas doses de bebida alcoólica o(a) Sr(a) consome?  | P029

Nos últimos trinta dias, o(a) Sr(a) chegou a consumir cinco ou mais doses de bebida alcoólica em uma única ocasião?  | P03201

Quando isso ocorreu, qual foi o número máximo de doses consumido em uma única ocasião? | P03202

Nos últimos doze meses, quando consumiu bebida alcoólica, o(a) Sr(a) dirigiu logo depois de beber?  | P03001

Nos últimos doze meses, quantas vezes o(a) Sr(a) deixou de trabalhar, realizar afazeres domésticos, ir à escola, curso ou faculdade, fazer compras, etc. porque bebeu demais?  | P03301

Nos últimos doze meses, quantas vezes, depois/após ter bebido, o(a) Sr(a) não conseguiu lembrar o que aconteceu?  | P03302

Nos últimos doze meses, algum parente, amigo ou profissional de saúde disse que você estava bebendo demais ou para você parar de beber?  | P03303

Nos últimos três meses, o(a) Sr(a) praticou algum tipo de exercício físico ou esporte?  | P034

Quantos dias por semana o(a) Sr(a) costuma  (costumava)praticar exercício físico ou esporte? | P035

Em geral, no dia que o(a) Sr(a) pratica exercício ou esporte, quanto tempo em horas dura essa atividade? Horas  | P03701

Em geral, no dia que o(a) Sr(a) pratica (praticava) exercício ou esporte, quanto tempo em minutos dura essa atividade?Minutos  | P03702

Qual o exercício físico ou esporte que o(a) Sr(a) pratica (praticava) com mais frequência? (Anotar apenas o primeiro citado)  | P036

No seu trabalho, o(a) Sr(a) anda bastante a pé?  | P038

No seu trabalho, o(a) Sr(a) faz faxina pesada, carrega peso ou faz outra atividade pesada que requer esforço físico intenso?  | P039

Em uma semana normal, em quantos dias, o(a) Sr(a) anda bastante a pé ou faz essas atividades pesadas ou que requerem esforço físico no seu trabalho? | P03904

Em um dia normal, quanto tempo o(a) Sr(a) passa andando bastante a pé ou realizando essas atividades pesadas ou que requerem esforço físico no seu trabalho?Horas  | P03905

Em um dia normal, quanto tempo o(a) Sr(a) passa andando bastante a pé ou realizando atividades essas atividades pesadas ou que requerem esforço físico no seu trabalho? Minutos | P03906

Para ir ou voltar do trabalho, o(a) Sr(a) faz algum trajeto a pé ou de bicicleta?  | P040

Quantos dias por semana o(a) Sr(a) faz algum trajeto a pé ou bicicleta?  | P04001

Quanto tempo o(a) Sr(a) gasta, por dia, para percorrer este trajeto a pé ou de bicicleta, considerando a ida e a volta do trabalho?Horas  | P04101

Quanto tempo o(a) Sr(a) gasta, por dia, para percorrer este trajeto a pé ou de bicicleta, considerando a ida e a volta do trabalho?Minutos | P04102

Nas suas atividades habituais (tais como ir a algum curso, escola ou clube ou levar alguém a algum curso, escola ou clube), quantos dias por semana o(a) Sr(a) faz alguma atividade que envolva deslocamento a pé ou bicicleta? (Exceto o trabalho) | P042

No dia em que o(a) Sr(a) faz essa(s) atividade(s), quanto tempo o(a) Sr(a) gasta no deslocamento a pé ou de bicicleta, considerando Ida e Volta?Horas | P04301

No dia em que o(a) Sr(a) faz essa(s) atividade(s), quanto tempo o(a) Sr(a) gasta no deslocamento a pé ou de bicicleta, considerando Ida e Volta?Minutos | P04302

Nas suas atividades domésticas, o(a) Sr(a) faz faxina pesada, carrega peso ou faz outra atividade pesada que requer esforço físico intenso? (não considerar atividade doméstica remunerada)  | P044

Em uma semana normal, nas suas atividades domésticas, em quantos dias o(a) Sr(a) faz faxina pesada ou realiza atividades que requerem esforço físico intenso? (não considerar atividade doméstica remunerada) | P04401

Quanto tempo gasta, por dia, realizando essas atividades domésticas pesadas ou que requerem esforço físico intenso? (não considerar atividade doméstica remunerada) Horas  | P04405

Quanto tempo gasta, por dia, realizando essas atividades domésticas pesadas ou que requerem esforço físico intenso?  | P04406

Em média, quantas horas por dia o(a) Sr(a) costuma ficar assistindo televisão?  | P04501

Em um dia, quantas horas do seu tempo livre (excluindo o trabalho), o(a) Sr(a) costuma usar computador, tablet ou celular para lazer, tais como: utilizar redes sociais, para ver notícias, vídeos, jogar etc?  | P04502

Perto do seu domicílio, existe algum lugar público (praça, parque, rua fechada, praia) para fazer caminhada, realizar exercício ou praticar esporte?  | P046

O(A) Sr(a) conhece algum programa público de estímulo à prática de atividade física no seu município?  | P04701

O(A) Sr(a) participa desse programa público de estímulo à prática de atividade física no seu município?  | P04801

Qual o principal motivo de não participar?  | P04902

Atualmente, o(a) Sr(a) fuma algum produto do tabaco?  | P050

E no passado, o(a) Sr(a) fumou algum produto do tabaco diariamente?  | P051

E no passado, o(a) Sr(a) fumou algum produto do tabaco?  | P052

Que idade o(a) Sr(a) tinha quando começou a fumar produto de tabaco diariamente?  | P053

Em média, quanto fuma por dia ou por semana Cigarros industrializados | P05401

Quantos por dia | P05402

Quantos por semana | P05403

Em média, quanto fuma por dia ou por semana Cigarros de palha ou enrolados a mão?  | P05404

Quantos por dia | P05405

Quantos por semana | P05406

Em média, quanto fuma por dia ou por semana Cigarros de cravo ou de Bali?  | P05407

Quantos por dia | P05408

Quantos por semana | P05409

Em média, quanto fuma por dia ou por semana Cachimbos (considere cachimbos cheios)?  | P05410

Quantos por dia | P05411

Quantos por semana | P05412

Em média, quanto fuma por dia ou por semana Charutos ou cigarrilhas?  | P05413

Quantos por dia | P05414

Quantos por semana | P05415

Em média, quanto fuma por dia ou por semana Narguilé (sessões)?  | P05416

Quantos por dia | P05417

Quantos por semana | P05418

Em média, quanto fuma por dia ou por semana Outro | P05419

Quantos por dia | P05421

Quantos por semana | P05422

Quanto tempo depois de acordar o(a) Sr(a) normalmente fuma pela primeira vez?  | P055

NA ÚLTIMA VEZ que o(a) Sr(a) comprou cigarros para uso próprio, quantos cigarros comprou? (Registre a quantidade e, quando necessário, registre os detalhes da unidade).  | P056

Quantidade de cigarros | P05601

Quantidade de maços | P05602

Quantos cigarros havia em cada maço?  | P05603

Quantidade de pacotes | P05604

Quantos maços havia em cada pacote?  | P05605

No total, quanto o(a) Sr(a) pagou por essa compra?  | P057

Em média, quantos cigarros industrializados o(a) Sr(a) fumava por dia ou por semana? | P058

Quantos por dia | P05801

Quantos por semana | P05802

Número de anos que parou de fumar | P05901

Número de meses que parou de fumar | P05902

Número de semanas que parou de fumar | P05903

Número de dias que parou de fumar | P05904


In [15]:
exp.load_variables("./data/my_variables_v2.pkl")
exp.print_module_len()

Modulo: C tem 4 atributos
Modulo: D tem 4 atributos
Modulo: F tem 3 atributos
Modulo: I tem 12 atributos
Modulo: J tem 19 atributos
Modulo: N tem 1 atributos
Modulo: P tem 37 atributos
Modulo: Q tem 11 atributos
Total: 91

In [16]:
exp.print_variables_per_module()

Modulo: C

Sexo | C006

Idade do morador na data de referência | C008

Cor ou raça | C009

Qual é o estado civil de ___?  | C011


 ---X---

Modulo: D

Sabe ler e escrever | D001

Frequenta escola ou creche | D00201

Qual foi o curso mais elevado que ___frequentou  | D00901

___concluiu este curso que frequentou  | D014


 ---X---

Modulo: F

Em (mês da pesquisa) ___ recebia normalmente rendimento de aposentadoria ou pensão de instituto de previdência federal (INSS), estadual, municipal, ou do governo federal, estadual, municipal? | F001011

Em (mês da pesquisa), ___ recebia normalmente rendimento de pensão alimentícia, doação ou mesada em dinheiro de pessoa que não morava no domicílio? | F007011

Em (mês da pesquisa), ___ recebia normalmente rendimento de aluguel ou arrendamento? | F008011


 ---X---

Modulo: I

tem algum plano odontológico particular, de empresa ou órgão público? | I00101

tem algum plano de saúde médico particular, de empresa ou órgão público? | I00102

Quantos? | I001021

Quem é o titular do plano de saúde médico (único ou principal)? | I00103

Há quanto tempo sem interrupção _____ possui esse plano de saúde (único ou principal)?  | I005

 ___ considera este plano de saúde:  | I006

O plano de saúde médico (único ou principal) que _____ possui é de instituição de assistência de servidor público (municipal, estadual ou militar)?  | I004

O plano de saúde (único ou principal) de assistência médica que ___ possui dá direito a consultas | I00401

O plano de saúde (único ou principal) de assistência médica que ___ possui dá direito a exames | I00402

O plano de saúde (único ou principal) de assistência médica que ___ possui dá direito a internações | I00403

O plano de saúde (único ou principal) de assistência médica que ___ possui dá direito a partos | I00404

Quem paga a mensalidade deste plano de saúde? | I010010


 ---X---

Modulo: J

 Nas duas últimas semanas, ___ deixou de realizar quaisquer de suas atividades habituais (trabalhar, ir à escola, brincar, afazeres domésticos etc.) por motivo da própria saúde | J002

Nas duas últimas semanas, quantos dias _____ deixou de realizar suas atividades habituais, por motivo da própria saúde | J003

 Qual foi o principal motivo de saúde que impediu ___ de realizar suas atividades habituais nas duas últimas semanas  | J00402

Este motivo de saúde estava relacionado ao trabalho | J00404

Nas duas últimas semanas___ esteve acamado (a) | J005

Nas duas últimas semanas, quantos dias _____ esteve acamado (a) | J006

Algum médico já deu o diagnóstico de alguma doença crônica, física ou mental, ou doença de longa duração (de mais de 6 meses de duração) a ___ | J007

Alguma dessas doenças limita de alguma forma suas atividades habituais (trabalhar, ir à escola, brincar, afazeres domésticos, etc.) | J00801

 ___ costuma procurar o mesmo lugar, mesmo médico ou mesmo serviço de saúde quando precisa de atendimento de saúde | J009

Quando está doente ou precisando de atendimento de saúde___ costuma procurar | J01002

Quando ____ consultou um médico pela última vez | J01101

Quando ___ consultou um dentista pela última vez | J01301

Nas duas últimas semanas, ___ procurou algum lugar, serviço ou profissional de saúde para atendimento relacionado à própria saúde | J014

Qual foi o motivo principal pelo qual ___ procurou atendimento relacionado à própria saúde nas duas últimas semanas | J01502

Onde ___ procurou o primeiro atendimento de saúde por este motivo nas duas últimas semanas | J01602

Nessa primeira vez que procurou atendimento de saúde por este motivo, nas duas últimas semanas | J01701

Por que motivo ___ não foi atendido(a) na primeira vez que procurou atendimento de saúde nas duas últimas semanas | J01802

Nas duas últimas semanas, quantas vezes ___ voltou a procurar atendimento de saúde por este mesmo motivo | J019

Onde ___ procurou o último atendimento de saúde por este motivo nas duas últimas semanas | J02002


 ---X---

Modulo: N


 ---X---

Modulo: P

Peso - Informado (em kg)
(3 inteiros e 1 casa decimal) | P00103

Altura - Informada (em cm)
(3 inteiros) | P00403

Em quantos dias da semana o(a) Sr(a) costuma comer feijão?  | P006

Em quantos dias da semana, o(a) Sr(a) costuma comer pelo menos um tipo de verdura ou legume (sem contar batata, mandioca, cará ou inhame) como alface, tomate, couve, cenoura, chuchu, berinjela, abobrinha?  | P00901

Em geral, o(a) Sr(a) costuma comer esse tipo de verdura ou legume:  | P01001

Em quantos dias da semana o(a) Sr(a) costuma comer carne vermelha (boi, porco, cabrito, bode, ovelha etc.)?  | P01101

Em quantos dias da semana o(a) Sr(a) costuma comer frango/galinha?  | P013

Em quantos dias da semana o(a) Sr(a) costuma comer peixe?  | P015

Em quantos dias da semana o(a) Sr(a) costuma tomar refrigerante?  | P02002

Que tipo de refrigerante o(a) Sr(a) costuma tomar?  | P02102

Em quantos dias da semana o(a) Sr(a) costuma tomar suco de caixinha/lata ou refresco em pó ?  | P02001

Em quantos dias da semana o(a) Sr(a) costuma tomar suco de fruta natural (incluída a polpa de fruta congelada)?  | P01601

Em quantos dias da semana o(a) Sr(a) costuma comer frutas?  | P018

Em geral, quantas vezes por dia o(a) Sr(a) come frutas?  | P019

Em quantos dias da semana o(a) Sr(a) costuma tomar leite? (de origem animal: vaca, cabra, búfala etc.)  | P023

Que tipo de leite o(a) Sr(a) costuma tomar?  | P02401

Em quantos dias da semana o(a) Sr(a) costuma comer alimentos doces como biscoito/bolacha recheado, chocolate, gelatina, balas e outros? | P02501

Em quantos dias da semana o(a) Sr(a) costuma substituir a refeição do almoço por lanches rápidos como sanduíches, salgados, pizza, cachorro quente, etc?  | P02602

Considerando a comida preparada na hora e os alimentos industrializados, o(a) Sr(a) acha que o seu consumo de sal é: | P02601

Nos últimos três meses, o(a) Sr(a) praticou algum tipo de exercício físico ou esporte?  | P034

Quantos dias por semana o(a) Sr(a) costuma  (costumava)praticar exercício físico ou esporte? | P035

Em geral, no dia que o(a) Sr(a) pratica exercício ou esporte, quanto tempo em horas dura essa atividade? Horas  | P03701

Em geral, no dia que o(a) Sr(a) pratica (praticava) exercício ou esporte, quanto tempo em minutos dura essa atividade?Minutos  | P03702

Qual o exercício físico ou esporte que o(a) Sr(a) pratica (praticava) com mais frequência? (Anotar apenas o primeiro citado)  | P036

No seu trabalho, o(a) Sr(a) anda bastante a pé?  | P038

No seu trabalho, o(a) Sr(a) faz faxina pesada, carrega peso ou faz outra atividade pesada que requer esforço físico intenso?  | P039

Em uma semana normal, em quantos dias, o(a) Sr(a) anda bastante a pé ou faz essas atividades pesadas ou que requerem esforço físico no seu trabalho? | P03904

Em um dia normal, quanto tempo o(a) Sr(a) passa andando bastante a pé ou realizando essas atividades pesadas ou que requerem esforço físico no seu trabalho?Horas  | P03905

Para ir ou voltar do trabalho, o(a) Sr(a) faz algum trajeto a pé ou de bicicleta?  | P040

Quantos dias por semana o(a) Sr(a) faz algum trajeto a pé ou bicicleta?  | P04001

Quanto tempo o(a) Sr(a) gasta, por dia, para percorrer este trajeto a pé ou de bicicleta, considerando a ida e a volta do trabalho?Horas  | P04101

Quanto tempo o(a) Sr(a) gasta, por dia, para percorrer este trajeto a pé ou de bicicleta, considerando a ida e a volta do trabalho?Minutos | P04102

Com que frequência o(a) Sr(a) costuma consumir alguma bebida alcoólica? | P027

Quantos dias por semana o(a) Sr(a) costuma consumir alguma bebida alcoólica?  | P02801

Em geral, no dia que o(a) Sr(a) bebe, quantas doses de bebida alcoólica o(a) Sr(a) consome?  | P029

Quando isso ocorreu, qual foi o número máximo de doses consumido em uma única ocasião? | P03202

Nos últimos doze meses, quando consumiu bebida alcoólica, o(a) Sr(a) dirigiu logo depois de beber?  | P03001


 ---X---

Modulo: Q

Algum médico já lhe deu o diagnóstico de hipertensão arterial (pressão alta)?  | Q00201

O(A) Sr(a) vai ao médico/serviço de saúde regularmente para acompanhamento da hipertensão arterial (pressão alta) ?  | Q00401

Qual o principal motivo do(a) Sr (a) não visitar o médico/serviço de saúde regularmente para acompanhamento da hipertensão arterial (pressão alta)?  | Q00502

O(A) Sr(a) pagou algum valor pelos medicamentos?  | Q010

Esse atendimento foi feito pelo SUS?  | Q015

Nas duas últimas semanas, o(a) Sr(a) tomou os medicamentos para controlar a hipertensão arterial (pressão alta)?  | Q00601

Algum médico já lhe deu o diagnóstico de diabetes?  | Q03001

Algum médico já lhe receitou insulina para controlar o Diabetes?  | Q03802

O(A) Sr(a) pagou algum valor pelos medicamentos orais para diabetes?  | Q03801

Em geral, em que grau a hipertensão ou alguma complicação da hipertensão limita as suas atividades habituais (como trabalhar, estudar, realizar afazeres domésticos etc.)?  | Q028

Quando foi a última vez que o(a) Sr(a) fez exame de sangue para medir a glicemia, isto é, o açúcar no sangue?  | Q02901


 ---X---

In [20]:
lista_col = ['Unidade da Federação',
 'Sexo',
 'Idade do morador na data de referência',
 'Cor ou raça',
 'Qual é o estado civil de ___? ',
 'Sabe ler e escrever',
 'Frequenta escola ou creche',
 'Qual foi o curso mais elevado que ___frequentou ',
 '___concluiu este curso que frequentou ',
 'Em (mês da pesquisa) ___ recebia normalmente rendimento de aposentadoria ou pensão de instituto de previdência federal (INSS), estadual, municipal, ou do governo federal, estadual, municipal?',
 'Em (mês da pesquisa), ___ recebia normalmente rendimento de pensão alimentícia, doação ou mesada em dinheiro de pessoa que não morava no domicílio?',
 'Em (mês da pesquisa), ___ recebia normalmente rendimento de aluguel ou arrendamento?',
 'tem algum plano odontológico particular, de empresa ou órgão público?',
 'tem algum plano de saúde médico particular, de empresa ou órgão público?',
 'De um modo geral, como é o estado de saúde de________',
 'Considerando saúde como um estado de bem-estar físico e mental, e não somente a ausência de doenças, como é o estado de saúde de _____________? ',
 ' Nas duas últimas semanas, ___ deixou de realizar quaisquer de suas atividades habituais (trabalhar, ir à escola, brincar, afazeres domésticos etc.) por motivo da própria saúde',
 'Algum médico já deu o diagnóstico de alguma doença crônica, física ou mental, ou doença de longa duração (de mais de 6 meses de duração) a ___',
 'Alguma dessas doenças limita de alguma forma suas atividades habituais (trabalhar, ir à escola, brincar, afazeres domésticos, etc.)',
 ' ___ costuma procurar o mesmo lugar, mesmo médico ou mesmo serviço de saúde quando precisa de atendimento de saúde',
 'Quando está doente ou precisando de atendimento de saúde___ costuma procurar',
 'Quando ____ consultou um médico pela última vez',
 'Quando ___ consultou um dentista pela última vez',
 'Nas duas últimas semanas, ___ procurou algum lugar, serviço ou profissional de saúde para atendimento relacionado à própria saúde',
 'Em geral, como o(a) Sr(a) avalia a sua saúde',
 'O(A) Sr(a) sabe seu peso? ',
 'Peso - Informado (em kg)\n(3 inteiros e 1 casa decimal)',
 'O(A) Sr(a) sabe sua altura? (mesmo que seja valor aproximado) ',
 'Altura - Informada (em cm)\n(3 inteiros)',
 'Em quantos dias da semana o(a) Sr(a) costuma comer feijão? ',
 'Em quantos dias da semana, o(a) Sr(a) costuma comer pelo menos um tipo de verdura ou legume (sem contar batata, mandioca, cará ou inhame) como alface, tomate, couve, cenoura, chuchu, berinjela, abobrinha? ',
 'Em quantos dias da semana o(a) Sr(a) costuma comer carne vermelha (boi, porco, cabrito, bode, ovelha etc.)? ',
 'Em quantos dias da semana o(a) Sr(a) costuma comer frango/galinha? ',
 'Em quantos dias da semana o(a) Sr(a) costuma comer peixe? ',
 'Em quantos dias da semana o(a) Sr(a) costuma tomar refrigerante? ',
 'Em quantos dias da semana o(a) Sr(a) costuma tomar suco de caixinha/lata ou refresco em pó ? ',
 'Em quantos dias da semana o(a) Sr(a) costuma tomar suco de fruta natural (incluída a polpa de fruta congelada)? ',
 'Em quantos dias da semana o(a) Sr(a) costuma comer frutas? ',
 'Em quantos dias da semana o(a) Sr(a) costuma tomar leite? (de origem animal: vaca, cabra, búfala etc.) ',
 'Que tipo de leite o(a) Sr(a) costuma tomar? ',
 'Em quantos dias da semana o(a) Sr(a) costuma comer alimentos doces como biscoito/bolacha recheado, chocolate, gelatina, balas e outros?',
 'Em quantos dias da semana o(a) Sr(a) costuma substituir a refeição do almoço por lanches rápidos como sanduíches, salgados, pizza, cachorro quente, etc? ',
 'Considerando a comida preparada na hora e os alimentos industrializados, o(a) Sr(a) acha que o seu consumo de sal é:',
 'Nos últimos três meses, o(a) Sr(a) praticou algum tipo de exercício físico ou esporte? ',
 'Com que frequência o(a) Sr(a) costuma consumir alguma bebida alcoólica?',
 'Algum médico já lhe deu o diagnóstico de hipertensão arterial (pressão alta)? ',
 'Algum médico já lhe deu o diagnóstico de diabetes? ',
 'Quando foi a última vez que o(a) Sr(a) fez exame de sangue para medir a glicemia, isto é, o açúcar no sangue? ']

exp.add_variables_by_description(lista_col)
exp.print_module_len()
len(lista_col)

lista_col2 = ['Unidade da Federação', 'Em geral, como o(a) Sr(a) avalia a sua saúde', 'Sexo', 'Idade do morador na data de referência', 'Cor ou raça', 'Qual é o estado civil de ___? ', 'Sabe ler e escrever', 'Frequenta escola ou creche', 'Qual foi o curso mais elevado que ___frequentou ', '___concluiu este curso que frequentou ', 'Em (mês da pesquisa) ___ recebia normalmente rendimento de aposentadoria ou pensão de instituto de previdência federal (INSS), estadual, municipal, ou do governo federal, estadual, municipal?', 'Em (mês da pesquisa), ___ recebia normalmente rendimento de pensão alimentícia, doação ou mesada em dinheiro de pessoa que não morava no domicílio?', 'Em (mês da pesquisa), ___ recebia normalmente rendimento de aluguel ou arrendamento?', 'tem algum plano odontológico particular, de empresa ou órgão público?', 'tem algum plano de saúde médico particular, de empresa ou órgão público?', ' Nas duas últimas semanas, ___ deixou de realizar quaisquer de suas atividades habituais (trabalhar, ir à escola, brincar, afazeres domésticos etc.) por motivo da própria saúde', 'Algum médico já deu o diagnóstico de alguma doença crônica, física ou mental, ou doença de longa duração (de mais de 6 meses de duração) a ___', 'Alguma dessas doenças limita de alguma forma suas atividades habituais (trabalhar, ir à escola, brincar, afazeres domésticos, etc.)', ' ___ costuma procurar o mesmo lugar, mesmo médico ou mesmo serviço de saúde quando precisa de atendimento de saúde', 'Quando está doente ou precisando de atendimento de saúde___ costuma procurar', 'Quando ____ consultou um médico pela última vez', 'Quando ___ consultou um dentista pela última vez', 'Nas duas últimas semanas, ___ procurou algum lugar, serviço ou profissional de saúde para atendimento relacionado à própria saúde', 'Peso - Informado (em kg)\n(3 inteiros e 1 casa decimal)', 'Altura - Informada (em cm)\n(3 inteiros)', 'Em quantos dias da semana o(a) Sr(a) costuma comer feijão? ', 'Em quantos dias da semana, o(a) Sr(a) costuma comer pelo menos um tipo de verdura ou legume (sem contar batata, mandioca, cará ou inhame) como alface, tomate, couve, cenoura, chuchu, berinjela, abobrinha? ', 'Em quantos dias da semana o(a) Sr(a) costuma comer carne vermelha (boi, porco, cabrito, bode, ovelha etc.)? ', 'Em quantos dias da semana o(a) Sr(a) costuma comer frango/galinha? ', 'Em quantos dias da semana o(a) Sr(a) costuma comer peixe? ', 'Em quantos dias da semana o(a) Sr(a) costuma tomar refrigerante? ', 'Em quantos dias da semana o(a) Sr(a) costuma tomar suco de caixinha/lata ou refresco em pó ? ', 'Em quantos dias da semana o(a) Sr(a) costuma tomar suco de fruta natural (incluída a polpa de fruta congelada)? ', 'Em quantos dias da semana o(a) Sr(a) costuma comer frutas? ', 'Em quantos dias da semana o(a) Sr(a) costuma tomar leite? (de origem animal: vaca, cabra, búfala etc.) ', 'Que tipo de leite o(a) Sr(a) costuma tomar? ', 'Em quantos dias da semana o(a) Sr(a) costuma comer alimentos doces como biscoito/bolacha recheado, chocolate, gelatina, balas e outros?', 'Em quantos dias da semana o(a) Sr(a) costuma substituir a refeição do almoço por lanches rápidos como sanduíches, salgados, pizza, cachorro quente, etc? ', 'Considerando a comida preparada na hora e os alimentos industrializados, o(a) Sr(a) acha que o seu consumo de sal é:', 'Nos últimos três meses, o(a) Sr(a) praticou algum tipo de exercício físico ou esporte? ', 'Com que frequência o(a) Sr(a) costuma consumir alguma bebida alcoólica?', 'Algum médico já lhe deu o diagnóstico de hipertensão arterial (pressão alta)? ', 'Algum médico já lhe deu o diagnóstico de diabetes? ', 'Quando foi a última vez que o(a) Sr(a) fez exame de sangue para medir a glicemia, isto é, o açúcar no sangue? ']
exp.add_variables_by_description(lista_col2)
exp.print_module_len()
len(lista_col2)

Descrição não encontrada: Unidade da Federação
Descrição não encontrada: Em geral, como o(a) Sr(a) avalia a sua saúde
Variáveis adicionadas com sucesso!
Modulo: C tem 4 atributos
Modulo: D tem 4 atributos
Modulo: F tem 3 atributos
Modulo: I tem 2 atributos
Modulo: J tem 10 atributos
Modulo: P tem 20 atributos
Modulo: Q tem 3 atributos
Total: 46
Descrição não encontrada: Unidade da Federação
Descrição não encontrada: Em geral, como o(a) Sr(a) avalia a sua saúde
Variáveis adicionadas com sucesso!
Modulo: C tem 4 atributos
Modulo: D tem 4 atributos
Modulo: F tem 3 atributos
Modulo: I tem 2 atributos
Modulo: J tem 8 atributos
Modulo: P tem 18 atributos
Modulo: Q tem 3 atributos
Total: 42

44

In [11]:
exp.print_variables_per_module()

Modulo: C

Sexo | C006

Idade do morador na data de referência | C008

Cor ou raça | C009

Qual é o estado civil de ___?  | C011


 ---X---

Modulo: D

Sabe ler e escrever | D001

Frequenta escola ou creche | D00201

Qual foi o curso mais elevado que ___frequentou  | D00901

___concluiu este curso que frequentou  | D014


 ---X---

Modulo: F

Em (mês da pesquisa) ___ recebia normalmente rendimento de aposentadoria ou pensão de instituto de previdência federal (INSS), estadual, municipal, ou do governo federal, estadual, municipal? | F001011

Em (mês da pesquisa), ___ recebia normalmente rendimento de pensão alimentícia, doação ou mesada em dinheiro de pessoa que não morava no domicílio? | F007011

Em (mês da pesquisa), ___ recebia normalmente rendimento de aluguel ou arrendamento? | F008011


 ---X---

Modulo: I

tem algum plano odontológico particular, de empresa ou órgão público? | I00101

tem algum plano de saúde médico particular, de empresa ou órgão público? | I00102


 ---X---

Modulo: J

De um modo geral, como é o estado de saúde de________ | J001

Considerando saúde como um estado de bem-estar físico e mental, e não somente a ausência de doenças, como é o estado de saúde de _____________?  | J00101

 Nas duas últimas semanas, ___ deixou de realizar quaisquer de suas atividades habituais (trabalhar, ir à escola, brincar, afazeres domésticos etc.) por motivo da própria saúde | J002

Algum médico já deu o diagnóstico de alguma doença crônica, física ou mental, ou doença de longa duração (de mais de 6 meses de duração) a ___ | J007

Alguma dessas doenças limita de alguma forma suas atividades habituais (trabalhar, ir à escola, brincar, afazeres domésticos, etc.) | J00801

 ___ costuma procurar o mesmo lugar, mesmo médico ou mesmo serviço de saúde quando precisa de atendimento de saúde | J009

Quando está doente ou precisando de atendimento de saúde___ costuma procurar | J01002

Quando ____ consultou um médico pela última vez | J01101

Quando ___ consultou um dentista pela última vez | J01301

Nas duas últimas semanas, ___ procurou algum lugar, serviço ou profissional de saúde para atendimento relacionado à própria saúde | J014


 ---X---

Modulo: N


 ---X---

Modulo: P

O(A) Sr(a) sabe seu peso?  | P00102

Peso - Informado (em kg)
(3 inteiros e 1 casa decimal) | P00103

O(A) Sr(a) sabe sua altura? (mesmo que seja valor aproximado)  | P00402

Altura - Informada (em cm)
(3 inteiros) | P00403

Em quantos dias da semana o(a) Sr(a) costuma comer feijão?  | P006

Em quantos dias da semana, o(a) Sr(a) costuma comer pelo menos um tipo de verdura ou legume (sem contar batata, mandioca, cará ou inhame) como alface, tomate, couve, cenoura, chuchu, berinjela, abobrinha?  | P00901

Em quantos dias da semana o(a) Sr(a) costuma comer carne vermelha (boi, porco, cabrito, bode, ovelha etc.)?  | P01101

Em quantos dias da semana o(a) Sr(a) costuma comer frango/galinha?  | P013

Em quantos dias da semana o(a) Sr(a) costuma comer peixe?  | P015

Em quantos dias da semana o(a) Sr(a) costuma tomar refrigerante?  | P02002

Em quantos dias da semana o(a) Sr(a) costuma tomar suco de caixinha/lata ou refresco em pó ?  | P02001

Em quantos dias da semana o(a) Sr(a) costuma tomar suco de fruta natural (incluída a polpa de fruta congelada)?  | P01601

Em quantos dias da semana o(a) Sr(a) costuma comer frutas?  | P018

Em quantos dias da semana o(a) Sr(a) costuma tomar leite? (de origem animal: vaca, cabra, búfala etc.)  | P023

Que tipo de leite o(a) Sr(a) costuma tomar?  | P02401

Em quantos dias da semana o(a) Sr(a) costuma comer alimentos doces como biscoito/bolacha recheado, chocolate, gelatina, balas e outros? | P02501

Em quantos dias da semana o(a) Sr(a) costuma substituir a refeição do almoço por lanches rápidos como sanduíches, salgados, pizza, cachorro quente, etc?  | P02602

Considerando a comida preparada na hora e os alimentos industrializados, o(a) Sr(a) acha que o seu consumo de sal é: | P02601

Nos últimos três meses, o(a) Sr(a) praticou algum tipo de exercício físico ou esporte?  | P034

Com que frequência o(a) Sr(a) costuma consumir alguma bebida alcoólica? | P027


 ---X---

Modulo: Q

Algum médico já lhe deu o diagnóstico de hipertensão arterial (pressão alta)?  | Q00201

Algum médico já lhe deu o diagnóstico de diabetes?  | Q03001

Quando foi a última vez que o(a) Sr(a) fez exame de sangue para medir a glicemia, isto é, o açúcar no sangue?  | Q02901


 ---X---

In [1]:
import pandas as pd

In [2]:
df = pd.read_excel("./data/dicionario_PNS_microdados_2019.xls", skiprows=1)

In [3]:
len(df)

5222

In [4]:
df.head(10)

,Posição inicial,Tamanho,Código\nda\nvariável,Quesito,Unnamed: 4,Categorias,Unnamed: 6
0,NaN,NaN,NaN,nº,descrição,Tipo,Descrição
1,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,Parte 1 - Identificação e Controle,NaN,NaN,NaN,NaN,NaN,NaN
3,1,2.0,V0001,NaN,Unidade da Federação,11,Rondônia
4,NaN,NaN,NaN,NaN,NaN,12,Acre
5,NaN,NaN,NaN,NaN,NaN,13,Amazonas
6,NaN,NaN,NaN,NaN,NaN,14,Roraima
7,NaN,NaN,NaN,NaN,NaN,15,Pará
8,NaN,NaN,NaN,NaN,NaN,16,Amapá
9,NaN,NaN,NaN,NaN,NaN,17,Tocantins

In [5]:
df = df.drop_duplicates().dropna(axis=0)

In [6]:
len(df)

1029

In [7]:
df.head(10)

,Posição inicial,Tamanho,Código\nda\nvariável,Quesito,Unnamed: 4,Categorias,Unnamed: 6
62,35,1.0,A001,A1,Tipo do domicílio,1,Casa
67,36,1.0,A002010,A2a,Qual é o material que predomina na construção ...,1,Alvenaria com revestimento ou taipa revestida
75,37,1.0,A003010,A3a,Material predominante na cobertura (telhado) d...,1,Telha sem laje de concreto
83,38,1.0,A004010,A4a,Qual é o material que predomina no piso deste ...,1,"Cerâmica, lajota ou pedra (inclusive outros pi..."
90,39,2.0,A01001,A10a,Quantos cômodos têm este domicílio,01 a 30,Cômodo(s) no domicílio
93,41,2.0,A011,A11,Quantos cômodos estão servindo permanentemente...,01 a 15,Cômodo(s) servindo de dormitório
96,43,1.0,A005010,A5a,Qual é a principal forma de abastecimento de á...,1,Rede geral de distribuição
104,44,1.0,A005012,A5b,Este domicílio está ligado à rede geral de dis...,1,Sim
108,45,1.0,A00601,A6a,A água utilizada neste domicílio chega,1,Canalizada em pelo menos um cômodo
113,46,1.0,A009010,A9a,A água utilizada para beber neste domicílio é,1,Filtrada

### Filtrando 

- Módulo A – Informações do domicílio
- Módulo B – Visitas domiciliares de Equipe de Saúde da Família e Agentes de Endemias
- **Módulo C – Características gerais dos moradores**
- **Módulo D – Características de educação das pessoas de 5 anos ou mais de idade**
- Módulo E – Trabalho dos moradores do domicílio
- **Módulo F – Rendimentos domiciliares**
- Módulo G – Pessoas com deficiências
- **Módulo I – Cobertura de plano de saúde**
- **Módulo J – Utilização de serviços de saúde**
- Módulo K – Saúde dos indivíduos com 60 anos ou mais e cobertura de mamografia entre mulheres de 50 anos ou mais
- Módulo L – Crianças com menos de 2 anos
- Módulo M – Outras características do trabalho e apoio social
- **Módulo N – Percepção do estado de saúde**
- Módulo O – Acidentes e violências
- **Módulo P – Estilos de vida**
- **Módulo Q – Doenças crônicas**
- Módulo R – Saúde da mulher
- Módulo S – Atendimento pré-natal
- Módulo U – Saúde bucal
- Módulo X – Atendimento médico

Renomeando Header

In [8]:
new_columns = {"Código\nda\nvariável":"Código da Váriavel", "Unnamed: 4" : "Quesito - Descrição", "Quesito": "Quesito - N°", "Categorias": "Categorias - Tipo", "Unnamed: 6" : "Categorias - Descrição"}
df = df.rename(columns=new_columns)
df.head(10)

,Posição inicial,Tamanho,Código da Váriavel,Quesito - N°,Quesito - Descrição,Categorias - Tipo,Categorias - Descrição
62,35,1.0,A001,A1,Tipo do domicílio,1,Casa
67,36,1.0,A002010,A2a,Qual é o material que predomina na construção ...,1,Alvenaria com revestimento ou taipa revestida
75,37,1.0,A003010,A3a,Material predominante na cobertura (telhado) d...,1,Telha sem laje de concreto
83,38,1.0,A004010,A4a,Qual é o material que predomina no piso deste ...,1,"Cerâmica, lajota ou pedra (inclusive outros pi..."
90,39,2.0,A01001,A10a,Quantos cômodos têm este domicílio,01 a 30,Cômodo(s) no domicílio
93,41,2.0,A011,A11,Quantos cômodos estão servindo permanentemente...,01 a 15,Cômodo(s) servindo de dormitório
96,43,1.0,A005010,A5a,Qual é a principal forma de abastecimento de á...,1,Rede geral de distribuição
104,44,1.0,A005012,A5b,Este domicílio está ligado à rede geral de dis...,1,Sim
108,45,1.0,A00601,A6a,A água utilizada neste domicílio chega,1,Canalizada em pelo menos um cômodo
113,46,1.0,A009010,A9a,A água utilizada para beber neste domicílio é,1,Filtrada

Filtrando o dataset por Módulos

In [9]:
df_my_categories = df[df["Quesito - N°"].str.startswith(("C", "D", "F", "I", "J", "P", "Q", "N"))]
print(f"Quantidade de elementos: {len(df_my_categories)}")

Quantidade de elementos: 513

In [10]:
df_my_categories.head(10)

,Posição inicial,Tamanho,Código da Váriavel,Quesito - N°,Quesito - Descrição,Categorias - Tipo,Categorias - Descrição
277,106,2.0,C004,C4,Condição no domicílio,01,Pessoa responsável pelo domicílio
297,108,1.0,C006,C6,Sexo,1,Homem
300,109,2.0,C00701,C7,Dia de nascimento,01 a 31,Dia de nascimento
303,111,2.0,C00702,C7,Mês de nascimento,01 a 12,Mês
306,113,4.0,C00703,C7,Ano de nascimento,ano atual - 130 a ano atual,Ano
309,117,3.0,C008,C8,Idade do morador na data de referência,000 a 130,Idade (em anos)
311,120,1.0,C009,C9,Cor ou raça,1,Branca
318,121,1.0,C01001,C10a,Cônjuge ou companheiro(a) mora em nesse domicí...,1,Sim
322,122,2.0,C010010,C10a,Número de ordem do cônjuge ou companheiro(a),01,morador 1
327,124,1.0,C013,C13,Cônjuge ou companheiro(a) mora em outro domicí...,1,Sim

Todas as varaiveis

In [11]:
all_descriptions = df_my_categories["Quesito - Descrição"]
for row in all_descriptions:
  print(row)

Condição no domicílio
Sexo
Dia de nascimento
Mês de nascimento
Ano de nascimento
Idade do morador na data de referência
Cor ou raça
Cônjuge ou companheiro(a) mora em nesse domicílio.
Número de ordem do cônjuge ou companheiro(a)
Cônjuge ou companheiro(a) mora em outro domicílio.
Qual é a natureza dessa união?
Esta união é registrada em cartório?
Foi realizada cerimônia religiosa para esta união?
___já viveu com cônjuge ou companheiro (a) antes?
Que idade ___tinha quando começou a viver com seu(sua) primeiro(a)/único(a) marido (mulher) ou companheiro(a)?
Que idade ___tinha quando começou a viver com seu(sua) primeiro(a)/único(a) marido (mulher) ou companheiro(a)?
Qual é o estado civil de ___?
Informante do Módulo C
Sabe ler e escrever
Frequenta escola ou creche
A escola que frequenta é da
Qual é o curso que frequenta
 Esse curso que ___ frequenta é dividido em
Qual é o ano/semestre/série que ___frequenta?
Qual é a etapa do ensino fundamental que ___ frequenta
 ___já concluiu algum outro curso superior de graduação
Anteriormente ___frequentou escola ou creche
Qual foi o curso mais elevado que ___frequentou
A duração deste curso que ___frequentou anteriormente era de
Este curso que ___ frequentou anteriormente era dividido em
concluiu, com aprovação, pelo menos o primeiro ano/semestre/série deste curso que frequentou
Qual foi o último ano/semestre/série que ___ concluiu, com aprovação, neste curso que frequentou
Qual foi a etapa de ensino fundamental que ___frequentou
___concluiu os anos iniciais deste curso que frequentou
___concluiu este curso que frequentou
Informante do Módulo D
Em (mês da pesquisa) ___ recebia normalmente rendimento de aposentadoria ou pensão de instituto de previdência federal (INSS), estadual, municipal, ou do governo federal, estadual, municipal?
Em (mês da pesquisa), ___ recebia normalmente rendimento de pensão alimentícia, doação ou mesada em dinheiro de pessoa que não morava no domicílio?
Em (mês da pesquisa), ___ recebia normalmente rendimento de aluguel ou arrendamento?
Informante do Módulo F
tem algum plano odontológico particular, de empresa ou órgão público?
tem algum plano de saúde médico particular, de empresa ou órgão público?
Quantos?
Quem é o titular do plano de saúde médico (único ou principal)?
Nº de ordem do titular
Há quanto tempo sem interrupção _____ possui esse plano de saúde (único ou principal)?
 ___ considera este plano de saúde:
O plano de saúde médico (único ou principal) que _____ possui é de instituição de assistência de servidor público (municipal, estadual ou militar)?
O plano de saúde (único ou principal) de assistência médica que ___ possui dá direito a consultas
O plano de saúde (único ou principal) de assistência médica que ___ possui dá direito a exames
O plano de saúde (único ou principal) de assistência médica que ___ possui dá direito a internações
O plano de saúde (único ou principal) de assistência médica que ___ possui dá direito a partos
Quem paga a mensalidade deste plano de saúde?
Informante do Módulo I
De um modo geral, como é o estado de saúde de________
Considerando saúde como um estado de bem-estar físico e mental, e não somente a ausência de doenças, como é o estado de saúde de _____________?
 Nas duas últimas semanas, ___ deixou de realizar quaisquer de suas atividades habituais (trabalhar, ir à escola, brincar, afazeres domésticos etc.) por motivo da própria saúde
Nas duas últimas semanas, quantos dias _____ deixou de realizar suas atividades habituais, por motivo da própria saúde
 Qual foi o principal motivo de saúde que impediu ___ de realizar suas atividades habituais nas duas últimas semanas
Este motivo de saúde estava relacionado ao trabalho
Nas duas últimas semanas___ esteve acamado (a)
Nas duas últimas semanas, quantos dias _____ esteve acamado (a)
Algum médico já deu o diagnóstico de alguma doença crônica, física ou mental, ou doença de longa duração (de mais de 6 meses de duração) a ___
Alguma dessas doenças limita de alguma forma suas atividades habituais (trabalhar, ir à escola, brincar, afazeres domésticos, etc.)
 ___ costuma procurar o mesmo lugar, mesmo médico ou mesmo serviço de saúde quando precisa de atendimento de saúde
Quando está doente ou precisando de atendimento de saúde___ costuma procurar
Quando ____ consultou um médico pela última vez
Quando ___ consultou um dentista pela última vez
Nas duas últimas semanas, ___ procurou algum lugar, serviço ou profissional de saúde para atendimento relacionado à própria saúde
Qual foi o motivo principal pelo qual ___ procurou atendimento relacionado à própria saúde nas duas últimas semanas
Onde ___ procurou o primeiro atendimento de saúde por este motivo nas duas últimas semanas
Nessa primeira vez que procurou atendimento de saúde por este motivo, nas duas últimas semanas
Por que motivo ___ não foi atendido(a) na primeira vez que procurou atendimento de saúde nas duas últimas semanas
Nas duas últimas semanas, quantas vezes ___ voltou a procurar atendimento de saúde por este mesmo motivo
Onde ___ procurou o último atendimento de saúde por este motivo nas duas últimas semanas
 Nessa última vez que procurou atendimento de saúde por este motivo, nas duas últimas semanas, ___ foi atendido (a)
Por que motivo ___ não foi atendido (a) nessa última vez que procurou atendimento de saúde nas duas últimas semanas
 Este serviço de saúde onde___ foi atendido era:
 Este atendimento de saúde de ___ foi coberto por algum plano de saúde
 ___ pagou algum valor por este atendimento de saúde recebido nas duas últimas semanas
O atendimento de ___ foi feito pelo SUS
Qual foi o principal atendimento de saúde que ___ recebeu?
 Neste atendimento de ___, foi receitado algum medicamento
 __conseguiu obter os medicamentos receitados? (Leia as opções de resposta)
Qual o principal motivo de ___ não ter conseguido obter todos os medicamentos receitados
Algum dos medicamentos foi coberto por plano de saúde
Algum dos medicamentos foi obtido no programa Aqui Tem Farmácia Popular
Algum dos medicamentos foi obtido em serviço público de saúde
 ___ pagou algum valor pelos medicamentos
Nas duas últimas semanas, por que motivo ___ não procurou serviço de saúde
Nos últimos 12 meses, ___ ficou internado(a) em hospital por 24 horas ou mais
Nos últimos 12 meses, quantas vezes ___ esteve internado(a)
Qual foi o principal atendimento de saúde que ___recebeu quando esteve internado(a) (pela última vez) nos doze últimos meses
Quanto tempo em meses o morador ficou internado
Quanto tempo em dias o morador ficou internado
O estabelecimento de saúde em que ___ esteve internado(a) pela última vez nos últimos 12 meses era
A última internação de ___ nos últimos 12 meses foi coberta por algum plano de saúde
 ___ pagou algum valor por esta última internação? (Entrevistador: se o(a) entrevistado(a) responder que pagou, mas teve reembolso total, marque a opção 2)
Esta última internação de ___ foi feita através do Sistema Único de Saúde (SUS)
Nos últimos 12 meses, ___ teve atendimento de urgência ou emergência no domicílio
Este atendimento foi coberto por algum plano de saúde
___pagou algum valor por este atendimento? (Entrevistador: se o(a) entrevistado(a) responder que pagou, mas teve reembolso total, marque a opção 2)
Este atendimento foi feito através do Sistema Único de Saúde (SUS)
Neste atendimento, ___ foi transportado por ambulância para um serviço de saúde
O transporte foi feito por
Nos últimos doze meses, ___ utilizou tratamento como acupuntura, homeopatia, plantas medicinais e fitoterapia, meditação, yoga, tai chi chuan, lian gong ou outra prática integrativa e complementar a saúde?
Qual tratamento _________ fez uso Acupuntura
Qual tratamento _________ fez uso Homeopatia
Qual tratamento _________ fez uso plantas medicinais e fitoterapia
Qual tratamento _________ fez uso auriculoterapia
Qual tratamento _________ fez uso meditação
Qual tratamento _________ fez uso Yoga
Qual tratamento _________ fez uso Tai chi chuan, Lian gong, Qi gong
Qual tratamento _________ fez uso Terapia comunitária integrativa
Qual tratamento _________ fez uso Outro
___ pagou algum valor por este(s) tratamento(s)
Este(s) tratamento(s) foi (foram) feito(s) através do Sistema Único de Saúde (SUS):
Informante do Módulo J
Em geral, como o(a) Sr(a) avalia a sua saúde
Considerando saúde como um estado de bem-estar físico e mental, e não somente a ausência de doenças, como você avalia o seu estado de saúde?
Quando o(a) Sr(a) sobe uma ladeira, um lance de escadas ou caminha rápido no plano, sente dor ou desconforto no peito
Quando o(a) Sr(a) caminha em lugar plano, em velocidade normal, sente dor ou desconforto no peito
 O que o(a) Sr(a) faz se sente dor ou desconforto no peito
Quando o(a) Sr(a) para, o que acontece com a dor ou desconforto no peito
O(A) Sr(a) pode me mostrar onde geralmente sente essa dor/desconforto no peito
Nas duas últimas semanas, com que frequência o(a) Sr(a) teve problemas no sono, como dificuldade para adormecer, acordar frequentemente à noite ou dormir mais do que de costume?
Nas duas últimas semanas, com que frequência o(a) Sr(a) teve problemas por não se sentir descansado(a) e disposto(a) durante o dia, sentindo-se cansado(a), sem ter energia?
Nas duas últimas semanas, com que frequência o(a) Sr(a) teve pouco interesse ou não senitiu prazer em fazer as coisas?
Nas duas últimas semanas, com que frequência o(a) Sr(a) teve problemas para se concentrar nas suas atividades habituais?
Nas duas últimas semanas, com que frequência o(a) Sr(a) teve problemas na alimentação, como ter falta de apetite ou comer muito mais do que de costume?
Nas duas últimas semanas, com que frequência o(a) Sr(a) teve lentidão para se movimentar ou falar, ou ao contrário ficou muito agitado(a) ou inquieto(a)?
Nas duas últimas semanas, com que frequência o(a) Sr(a) se sentiu deprimido(a), “pra baixo” ou sem perspectiva?
Nas duas últimas semanas, com que frequência o(a) Sr(a) se sentiu mal consigo mesmo, se achando um fracasso ou achando que decepcionou sua família?
Nas duas últimas semanas, com que frequência o(a) Sr(a) pensou em se ferir de alguma maneira ou achou que seria melhor estar morto?
O(A) Sr(a) sabe seu peso?
Peso - Informado (em kg)
(3 inteiros e 1 casa decimal)
Quanto tempo faz que o(a) Sr(a) se pesou da última vez?
O(A) Sr(a) sabe sua altura? (mesmo que seja valor aproximado)
Altura - Informada (em cm)
(3 inteiros)
A Sra está grávida no momento?
Ontem o(a) Sr(a) comeu arroz, macarrão, polenta, cuscuz ou milho verde.
Batata comum, mandioca/aipim/macaxeira, cará ou inhame.
Feijão, ervilha, lentilha ou grão de bico.
Carne de boi, porco, frango, peixe
Ovo (frito, cozido ou mexido ).
Alface, couve, brócolis, agrião ou espinfre.
Abóbora, cenoura, batata doce ou quiabo/caruru.
Tomate, pepino, abobrinha, berinjela, chuchu ou beterraba.
Mamão, manga, melão amarelo ou pequi.
Laranja, banana, maçã, abacaxi.
Leite
Amendoim, castanha de caju ou castanha do Brasil/Pará
ONTEM o(a) Sr(a) tomou ou comeu:Refrigerante
Suco de fruta em caixinha ou lata ou refresco em pó.
 Bebida achocolatada ou iogurte com sabor.
Salgadinho de pacote ou biscoito/bolacha salgado.
Biscoito/bolacha doce ou recheado ou bolo de pacote.
Sorvete, chocolate, gelatina, flan ou outra sobremesa industrializada.
Salsicha, linguiça, mortadela ou presunto.
Pão de forma, de cachorro-quente ou de hambúrguer.
Margarina, maionese, ketchup ou outros molhos industrializados.
Macarrão instantâneo, sopa de pacote, lasanha congelada ou outro prato congelado comprado pronto industrilizado.
Em quantos dias da semana o(a) Sr(a) costuma comer feijão?
Em quantos dias da semana, o(a) Sr(a) costuma comer pelo menos um tipo de verdura ou legume (sem contar batata, mandioca, cará ou inhame) como alface, tomate, couve, cenoura, chuchu, berinjela, abobrinha?
Em geral, o(a) Sr(a) costuma comer esse tipo de verdura ou legume:
Em quantos dias da semana o(a) Sr(a) costuma comer carne vermelha (boi, porco, cabrito, bode, ovelha etc.)?
Em quantos dias da semana o(a) Sr(a) costuma comer frango/galinha?
Em quantos dias da semana o(a) Sr(a) costuma comer peixe?
Em quantos dias da semana o(a) Sr(a) costuma tomar suco de caixinha/lata ou refresco em pó ?
Que tipo de suco de caixinha/lata ou refresco em pó o(a) Sr(a) costuma tomar? (Ler as opções de resposta)
Em quantos dias da semana o(a) Sr(a) costuma tomar suco de fruta natural (incluída a polpa de fruta congelada)?
Em quantos dias da semana o(a) Sr(a) costuma comer frutas?
Em geral, quantas vezes por dia o(a) Sr(a) come frutas?
Em quantos dias da semana o(a) Sr(a) costuma tomar refrigerante?
Que tipo de refrigerante o(a) Sr(a) costuma tomar?
Em quantos dias da semana o(a) Sr(a) costuma tomar leite? (de origem animal: vaca, cabra, búfala etc.)
Que tipo de leite o(a) Sr(a) costuma tomar?
Em quantos dias da semana o(a) Sr(a) costuma comer alimentos doces como biscoito/bolacha recheado, chocolate, gelatina, balas e outros?
Em quantos dias da semana o(a) Sr(a) costuma substituir a refeição do almoço por lanches rápidos como sanduíches, salgados, pizza, cachorro quente, etc?
Considerando a comida preparada na hora e os alimentos industrializados, o(a) Sr(a) acha que o seu consumo de sal é:
Com que frequência o(a) Sr(a) costuma consumir alguma bebida alcoólica?
Quantos dias por semana o(a) Sr(a) costuma consumir alguma bebida alcoólica?
Em geral, no dia que o(a) Sr(a) bebe, quantas doses de bebida alcoólica o(a) Sr(a) consome?
Nos últimos trinta dias, o(a) Sr(a) chegou a consumir cinco ou mais doses de bebida alcoólica em uma única ocasião?
Quando isso ocorreu, qual foi o número máximo de doses consumido em uma única ocasião?
Nos últimos doze meses, quando consumiu bebida alcoólica, o(a) Sr(a) dirigiu logo depois de beber?
Nos últimos doze meses, quantas vezes o(a) Sr(a) deixou de trabalhar, realizar afazeres domésticos, ir à escola, curso ou faculdade, fazer compras, etc. porque bebeu demais?
Nos últimos doze meses, quantas vezes, depois/após ter bebido, o(a) Sr(a) não conseguiu lembrar o que aconteceu?
Nos últimos doze meses, algum parente, amigo ou profissional de saúde disse que você estava bebendo demais ou para você parar de beber?
Nos últimos três meses, o(a) Sr(a) praticou algum tipo de exercício físico ou esporte?
Quantos dias por semana o(a) Sr(a) costuma  (costumava)praticar exercício físico ou esporte?
Em geral, no dia que o(a) Sr(a) pratica exercício ou esporte, quanto tempo em horas dura essa atividade? Horas
Em geral, no dia que o(a) Sr(a) pratica (praticava) exercício ou esporte, quanto tempo em minutos dura essa atividade?Minutos
Qual o exercício físico ou esporte que o(a) Sr(a) pratica (praticava) com mais frequência? (Anotar apenas o primeiro citado)
No seu trabalho, o(a) Sr(a) anda bastante a pé?
No seu trabalho, o(a) Sr(a) faz faxina pesada, carrega peso ou faz outra atividade pesada que requer esforço físico intenso?
Em uma semana normal, em quantos dias, o(a) Sr(a) anda bastante a pé ou faz essas atividades pesadas ou que requerem esforço físico no seu trabalho?
Em um dia normal, quanto tempo o(a) Sr(a) passa andando bastante a pé ou realizando essas atividades pesadas ou que requerem esforço físico no seu trabalho?Horas
Em um dia normal, quanto tempo o(a) Sr(a) passa andando bastante a pé ou realizando atividades essas atividades pesadas ou que requerem esforço físico no seu trabalho? Minutos
Para ir ou voltar do trabalho, o(a) Sr(a) faz algum trajeto a pé ou de bicicleta?
Quantos dias por semana o(a) Sr(a) faz algum trajeto a pé ou bicicleta?
Quanto tempo o(a) Sr(a) gasta, por dia, para percorrer este trajeto a pé ou de bicicleta, considerando a ida e a volta do trabalho?Horas
Quanto tempo o(a) Sr(a) gasta, por dia, para percorrer este trajeto a pé ou de bicicleta, considerando a ida e a volta do trabalho?Minutos
Nas suas atividades habituais (tais como ir a algum curso, escola ou clube ou levar alguém a algum curso, escola ou clube), quantos dias por semana o(a) Sr(a) faz alguma atividade que envolva deslocamento a pé ou bicicleta? (Exceto o trabalho)
No dia em que o(a) Sr(a) faz essa(s) atividade(s), quanto tempo o(a) Sr(a) gasta no deslocamento a pé ou de bicicleta, considerando Ida e Volta?Horas
No dia em que o(a) Sr(a) faz essa(s) atividade(s), quanto tempo o(a) Sr(a) gasta no deslocamento a pé ou de bicicleta, considerando Ida e Volta?Minutos
Nas suas atividades domésticas, o(a) Sr(a) faz faxina pesada, carrega peso ou faz outra atividade pesada que requer esforço físico intenso? (não considerar atividade doméstica remunerada)
Em uma semana normal, nas suas atividades domésticas, em quantos dias o(a) Sr(a) faz faxina pesada ou realiza atividades que requerem esforço físico intenso? (não considerar atividade doméstica remunerada)
Quanto tempo gasta, por dia, realizando essas atividades domésticas pesadas ou que requerem esforço físico intenso? (não considerar atividade doméstica remunerada) Horas
Quanto tempo gasta, por dia, realizando essas atividades domésticas pesadas ou que requerem esforço físico intenso?
Em média, quantas horas por dia o(a) Sr(a) costuma ficar assistindo televisão?
Em um dia, quantas horas do seu tempo livre (excluindo o trabalho), o(a) Sr(a) costuma usar computador, tablet ou celular para lazer, tais como: utilizar redes sociais, para ver notícias, vídeos, jogar etc?
Perto do seu domicílio, existe algum lugar público (praça, parque, rua fechada, praia) para fazer caminhada, realizar exercício ou praticar esporte?
O(A) Sr(a) conhece algum programa público de estímulo à prática de atividade física no seu município?
O(A) Sr(a) participa desse programa público de estímulo à prática de atividade física no seu município?
Qual o principal motivo de não participar?
Atualmente, o(a) Sr(a) fuma algum produto do tabaco?
E no passado, o(a) Sr(a) fumou algum produto do tabaco diariamente?
E no passado, o(a) Sr(a) fumou algum produto do tabaco?
Que idade o(a) Sr(a) tinha quando começou a fumar produto de tabaco diariamente?
Em média, quanto fuma por dia ou por semana Cigarros industrializados
Quantos por dia
Quantos por semana
Em média, quanto fuma por dia ou por semana Cigarros de palha ou enrolados a mão?
Quantos por dia
Quantos por semana
Em média, quanto fuma por dia ou por semana Cigarros de cravo ou de Bali?
Quantos por dia
Quantos por semana
Em média, quanto fuma por dia ou por semana Cachimbos (considere cachimbos cheios)?
Quantos por dia
Quantos por semana
Em média, quanto fuma por dia ou por semana Charutos ou cigarrilhas?
Quantos por dia
Quantos por semana
Em média, quanto fuma por dia ou por semana Narguilé (sessões)?
Quantos por dia
Quantos por semana
Em média, quanto fuma por dia ou por semana Outro
Quantos por dia
Quantos por semana
Quanto tempo depois de acordar o(a) Sr(a) normalmente fuma pela primeira vez?
NA ÚLTIMA VEZ que o(a) Sr(a) comprou cigarros para uso próprio, quantos cigarros comprou? (Registre a quantidade e, quando necessário, registre os detalhes da unidade).
Quantidade de cigarros
Quantidade de maços
Quantos cigarros havia em cada maço?
Quantidade de pacotes
Quantos maços havia em cada pacote?
No total, quanto o(a) Sr(a) pagou por essa compra?
Em média, quantos cigarros industrializados o(a) Sr(a) fumava por dia ou por semana?
Quantos por dia
Quantos por semana
Número de anos que parou de fumar
Número de meses que parou de fumar
Número de semanas que parou de fumar
Número de dias que parou de fumar
Nos últimos doze meses, durante algum atendimento, por médico ou outro profissional de saúde, foi perguntado se o(a) Sr(a) fumava?
Nos últimos doze meses, durante algum desses atendimentos o(a) Sr(a) foi aconselhado a parar de fumar?
Durante os últimos doze meses, o(a) Sr(a) tentou parar de fumar?
Durante os últimos doze meses, quando o(a) Sr(a) tentou parar de fumar, usou aconselhamento por profissional de saúde incluindo unidades de saúde que oferecem tratamento para parar de fumar?
O(A) Sr(a) pagou algum valor por esse aconselhamento?
Esse aconselhamento foi feito pelo SUS?

Filtrando atributos por modulos

In [12]:
# "C", "D", "F", "I", "J", "P", "Q"
atributos_por_modulos = {
  "C": [],
  "D": [],
  "F": [],
  "I": [],
  "J": [],
  "N": [],
  "P": [],
  "Q": [],
}

for row in df_my_categories.itertuples():
    index_atr = row[3]
    atributos_por_modulos[index_atr[0]].append(row)   
  

total = 0
for mod, values in atributos_por_modulos.items():
  print(f"Modulo: {mod} tem {len(values)} atributos")
  total += len(values)
print(f"Total: {total}")

Modulo: C tem 18 atributos
Modulo: D tem 18 atributos
Modulo: F tem 4 atributos
Modulo: I tem 14 atributos
Modulo: J tem 64 atributos
Modulo: N tem 16 atributos
Modulo: P tem 143 atributos
Modulo: Q tem 236 atributos
Total: 513

Filtrando por Atributos

In [12]:
from lib.utils import save_variables


atributos_manter = {
  "C":  ["C006", "C008", "C009", "C011"],
  "D": ["D001", "D00201", "D00901", "D014"],
  "F": ["F001011", "F007011", "F008011"],
  "I": ["I00101", "I00102", "I001021", "I00103", "I005", "I006", "I004", "I00401", "I00402", "I00403", "I00404", "I010010"],
  "J": ["J002","J003","J00402","J00404","J005", "J006","J007","J00801","J009","J01002","J01101","J01301","J014","J01502","J01602", "J01701", "J01802", "J019", "J02002",],
  "N": ["N001"],
  "P": ["P00103","P00403", "P006","P00901","P01001","P01101","P013","P015","P02002","P02102","P02001","P01601","P018","P019","P023","P02401","P02501","P02602","P02601","P034","P035","P03701","P03702","P036","P038","P039","P03904","P03905","P040","P04001","P04101", "P04102" ,"P027","P02801","P029","P03202","P03001"],
  "Q": ["Q00201","Q00401","Q00502", "Q010","Q015","Q00601", "Q03001","Q03802", "Q03801", "Q028", "Q02901"]
}
save_variables("./data/my_variables_v2.pkl", atributos_manter)

In [14]:
todas = []
duplicatas = []

for categoria, lista in atributos_manter.items():
    for item in lista:
        if item in todas and item not in duplicatas:
            duplicatas.append(item)
        todas.append(item)

if duplicatas:
    print("Strings duplicadas encontradas:")
    for d in duplicatas:
        print(" -", d)
else:
    print("Nenhuma string repetida encontrada!")

Nenhuma string repetida encontrada!

In [15]:
total = 0
for mod, values in atributos_manter.items():
  print(f"Modulo: {mod} tem {len(values)} atributos")
  total += len(values)
print(f"Total: {total}")

Modulo: C tem 4 atributos
Modulo: D tem 4 atributos
Modulo: F tem 3 atributos
Modulo: I tem 12 atributos
Modulo: J tem 21 atributos
Modulo: N tem 1 atributos
Modulo: P tem 39 atributos
Modulo: Q tem 11 atributos
Total: 95